services:
  api:
    build: .
    container_name: api
    env_file:
      - ./mysql/.env
    ports:
      - "127.0.0.1:5000:8080"
    depends_on:
      - sql
    networks:
      - backend
  sql:
    build: ./mysql/init
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_HOST="%"
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    driver: bridge