services:
  api:
    build: .
    container_name: api
    env_file:
      - ./mysql/.env
      - ./influxdb2/.env
    ports:
      - "127.0.0.1:5000:8080"
    volumes:
      - ./shared_config:/var/lib/shared_config:r
    depends_on:
      - sql
      - influxdb2
    networks:
      - backend
  sql:
    build: ./mysql/init
    restart: always
    container_name: mysql
    environment:
      - MYSQL_ROOT_HOST="%"
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend
  influxdb2:
    build: ./influxdb2/init
    container_name: influxdb2
    env_file:
      - ./influxdb2/.env
    volumes:
      - ./influxdb2/data:/var/lib/influxdb2:rw
      - ./influxdb2/config:/etc/influxdb2:rw
      - ./shared_config:/var/lib/influxdb2/shared_config:rw
    networks:
      - backend
networks:
  backend:
    driver: bridge